INSERT INTO district_table (id, name) VALUES
(1, 'Saharanpur'),
(2, 'Muzaffarnagar'),
(3, 'Bijnor'),
(4, 'Moradabad'),
(5, 'Rampur'),
(6, 'Jyotiba Phule Nagar'),
(7, 'Meerut'),
(8, 'Baghpat'),
(9, 'Ghaziabad'),
(11, 'Bulandshahr'),
(12, 'Aligarh'),
(13, 'Mahamaya Nagar'),
(14, 'Mathura'),
(15, 'Agra'),
(16, 'Firozabad'),
(18, 'Budaun'),
(19, 'Bareilly'),
(20, 'Pilibhit'),
(21, 'Shahjahanpur'),
(22, 'Kheri'),
(23, 'Sitapur'),
(24, 'Hardoi'),
(25, 'Unnao'),
(26, 'Lucknow'),
(28, 'Farrukhabad'),
(29, 'Kannauj'),
(30, 'Etawah'),
(33, 'Kanpur Nagar'),
(34, 'Jalaun'),
(35, 'Jhansi'),
(36, 'Lalitpur'),
(38, 'Mahoba'),
(39, 'Banda'),
(41, 'Fatehpur'),
(42, 'Pratapgarh'),
(43, 'Kaushambi'),
(44, 'Allahabad'),
(45, 'Bara Banki'),
(47, 'Ambedkar Nagar'),
(48, 'Sultanpur'),
(50, 'Shrawasti'),
(51, 'Balrampur'),
(52, 'Gonda'),
(53, 'Siddharthnagar'),
(55, 'Sant Kabir Nagar'),
(57, 'Gorakhpur'),
(58, 'Kushinagar'),
(59, 'Deoria'),
(60, 'Azamgarh'),
(61, 'Mau'),
(63, 'Jaunpur'),
(64, 'Ghazipur'),
(65, 'Chandauli'),
(66, 'Varanasi'),
(67, 'Sant Ravidas Nagar (Bhadohi)'),
(68, 'Mirzapur'),
(70, 'Etah'),
(71, 'Kanshiram Nagar');
